const fs=require('node:fs'),path=require('node:path');
const games=require('../content/games.cjs'),articles=require('../content/articles.cjs');
const root=path.resolve(__dirname,'..'),out=process.env.SSALMUK_BUILD_OUT||root;
const date='2026-09-14',sourcesChecked='2026-09-13',base='https://ssalmukindex.com',files=new Map();
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const para=items=>items.map(p=>'<p>'+esc(p)+'</p>').join('\n');
const table=(heads,rows)=>'<div class="table-scroll"><table><thead><tr>'+heads.map(h=>'<th scope="col">'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(c=>'<td>'+esc(c)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';
function sources(items){return items.length?'<section id="sources"><h2>확인한 출처와 범위</h2><p class="meta">확인일 '+sourcesChecked+' · 공식 자료의 설명과 이 사이트의 해석·계산 예시는 구분됩니다. 발표 당시 조건은 현재 조건과 다를 수 있습니다.</p><ol class="source-list">'+items.map(([title,url,note])=>'<li><a href="'+esc(url)+'" rel="noopener noreferrer">'+esc(title)+'</a><span>'+esc(note)+'</span></li>').join('')+'</ol></section>':'';}
function navigation(current){return [['/','홈'],['/games/','게임별 가이드'],['/calculator.html','기록 계산기'],['/blog/','분석 노트'],['/guide.html','이용 안내']].map(([url,title])=>'<a href="'+url+'"'+(url===current?' aria-current="page"':'')+'>'+title+'</a>').join('');}
function page(file,title,description,body,{article=false,section='',noindex=false,script=''}={}){
 const url=base+(file==='index.html'?'/':file.endsWith('/index.html')?'/'+file.slice(0,-10):'/'+file);
 const pathname=new URL(url).pathname;
 const schema={'@context':'https://schema.org','@type':article?'Article':'WebPage',name:title,description,url,inLanguage:'ko',dateModified:date,publisher:{'@type':'Organization',name:'쌀먹지수',url:base+'/about.html'}};
 if(article){schema.headline=title;schema.author={'@type':'Organization',name:'쌀먹지수',url:base+'/about.html'};}
 const html=`<!doctype html>
<html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#0b0e10"><title>${esc(title)} — 쌀먹지수</title><meta name="description" content="${esc(description)}"><meta name="robots" content="${noindex?'noindex,follow':'index,follow,max-image-preview:large'}"><meta name="google-site-verification" content="SXVf-m8jIWeAUG0y9I19GzX5hSdY1vUqVhLyyeK1V_g"><meta name="google-adsense-account" content="ca-pub-3692243854038260"><link rel="canonical" href="${url}"><link rel="icon" href="/favicon-32.png" type="image/png"><link rel="stylesheet" href="/assets/site.css"><meta property="og:type" content="${article?'article':'website'}"><meta property="og:site_name" content="쌀먹지수"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${url}"><meta property="og:locale" content="ko_KR"><meta name="twitter:card" content="summary"><script type="application/ld+json">${JSON.stringify(schema).replace(/</g,'\\u003c')}</script><script src="/assets/site.js" defer></script>${script}</head>
<body><a class="skip" href="#main">본문으로 건너뛰기</a><header class="site-header"><div class="wrap header-inner"><a class="brand" href="/">🌾 쌀먹<span>지수</span></a><nav aria-label="주 메뉴">${navigation(pathname)}</nav></div></header><main id="main" class="wrap">${body}</main><footer class="site-footer"><div class="wrap"><nav aria-label="사이트 안내"><a href="/about.html">운영자·사이트 소개</a><a href="/editorial.html">편집·출처 기준</a><a href="/data-integrity.html">정정 기록</a><a href="/contact.html">문의</a><a href="/privacy.html">개인정보처리방침</a></nav><p>© 2026 쌀먹지수 · 게임 경제와 개인 기록을 읽는 도구<br>공식 자료에 근거한 사실과 계산 예시를 구분합니다. 게임 재화를 원화로 자동 환산하거나 수익을 보장하지 않습니다.</p></div></footer></body></html>\n`;
 files.set(file,html);return url;
}
function articlePage(file,title,description,body,refs=[],section='분석 노트'){
 const url=section==='게임별 가이드'?'/games/':'/blog/';
 const headings=[...body.matchAll(/<h2 id="([^"]+)">([^<]+)<\/h2>/g)];
 page(file,title,description,`<div class="breadcrumb"><a href="/">홈</a> / <a href="${url}">${section}</a></div><div class="article-layout"><article class="article"><span class="eyebrow">${section}</span><h1>${esc(title)}</h1><p class="meta">작성: 쌀먹지수 · 내용 확인/수정 ${date} · <a href="/editorial.html">자료와 작성 기준</a></p>${body}${sources(refs)}<hr class="divider"><p><a href="/calculator.html">내 기록으로 계산하기 →</a> · <a href="/contact.html">이 문서의 오류 제보</a></p></article><aside class="toc" aria-label="문서 목차"><strong>이 문서에서</strong>${headings.map(m=>'<a href="#'+m[1]+'">'+m[2]+'</a>').join('')}${refs.length?'<a href="#sources">출처와 확인 범위</a>':''}<hr class="divider"><a href="/blog/ssalmuk-methodology.html">계산 방법과 한계</a><a href="/blog/beginner-guide-2026.html">처음 기록하는 방법</a></aside></div>`,{article:true,section});
}
const gameCard=g=>`<section class="card" data-search="${esc(g.name+' '+g.topic+' '+g.category)}"><span class="tag">${esc(g.category)} · ${esc(g.unit)}</span><h3><a href="/games/${g.slug}.html">${esc(g.name)}</a></h3><p>${esc(g.topic)}</p></section>`;
const blogCard=a=>`<section class="card"><span class="tag">분석 노트</span><h3><a href="/blog/${a.slug}.html">${esc(a.title)}</a></h3><p>${esc(a.description)}</p></section>`;

page('index.html','게임 경제를 읽고, 내 기록으로 비교하세요','게임별 공식 거래 구조와 비용·시간 분석, 개인 플레이 기록 계산기. 출처 없는 시급 순위 대신 직접 확인할 수 있는 자료를 제공합니다.',`
<section class="hero"><span class="eyebrow">GAME ECONOMY · PERSONAL RECORDS</span><h1>얼마나 얻었는지보다,<br>무엇이 남았는지.</h1><p class="lead">게임에서 얻은 재화, 실제로 판매한 금액, 들인 시간을 나눠 보세요. 공식 자료로 거래 구조를 확인하고, 내 기록으로 활동의 효율을 비교합니다.</p><div class="actions"><a class="button primary" href="/calculator.html">내 기록 계산하기</a><a class="button" href="/games/">게임별 확인할 항목</a></div><p class="meta">게임 내 재화와 현금은 별도 단위입니다. 계산 예시는 실제 플레이 성과가 아닙니다.</p></section>
<div class="steps"><section><h3>거래 구조부터 확인</h3><p>판매 가능 조건, 보증금, 수수료, 반복 제한을 게임별 공식 출처와 함께 살펴봅니다.</p></section><section><h3>판매·비용·시간을 기록</h3><p>판매 대기 물품과 실제 수령액을 나누고, 준비와 중단 시간까지 남깁니다.</p></section><section><h3>같은 조건끼리 비교</h3><p>게임·단위·기록 유형을 구분해 계산합니다. 다른 재화를 원화 시급 하나로 묶지 않습니다.</p></section></div>
<div class="section-head"><h2>게임마다 먼저 확인할 것</h2><a href="/games/">11개 가이드 모두 보기 →</a></div><div class="cards">${games.slice(0,6).map(gameCard).join('')}</div>
<section class="article"><h2>정산 전 10,000과 실제 순증가 8,000은 다릅니다</h2><p>계산 설명을 위해 수입 10,000, 수수료 500, 소모 비용 1,500, 경과 시간 90분을 가정해 봅니다. 손에 남는 순증가는 8,000이고, 시간당은 약 5,333입니다. 미판매 물품을 더하거나 준비 시간을 빼면 다른 결과가 됩니다.</p><div class="formula"><span class="example-label">가상 계산 예시</span><br>(10,000 − 500 − 1,500) × 60 ÷ 90 ≈ 5,333.33 단위/h</div><p>같은 ‘골드’라도 게임이 다르면 함께 합산하지 않습니다. 이미 수수료가 빠진 수령액을 수입으로 입력한 경우 수수료를 다시 차감하지 않습니다. <a href="/blog/ssalmuk-methodology.html">계산식과 입력 기준</a>을 공개해 누구나 같은 결과를 확인할 수 있게 했습니다.</p></section>
<div class="section-head"><h2>숫자를 읽는 분석 노트</h2><a href="/blog/">전체 글 보기 →</a></div><div class="cards">${[articles[0],articles[2],articles[4]].map(blogCard).join('')}</div>
<section class="article"><h2>이 사이트가 제공하는 자료의 범위</h2><p>쌀먹지수는 공식 시스템 안내를 근거로 거래·정산 조건을 설명하고, 직접 설계한 기록표와 계산 예시로 비교 방법을 다룹니다. 일반 이용자의 원화 수익을 검증한 표본은 현재 공개하지 않습니다. 개인 기록 계산기의 저장값은 해당 브라우저에만 남으며 사이트 전체의 랭킹으로 전송되지 않습니다.</p><p>플레이 경험이 없는 내용을 체험담으로 쓰거나, 자동으로 만든 닉네임·댓글·투표 수를 이용자 참여로 보여주지 않습니다. 실측이 필요한 질문에는 확인할 항목과 부족한 근거를 명시합니다.</p><div class="note"><strong>2026-09-14 정정 안내</strong><p>근거가 확인되지 않은 원화 시급 순위와 자동 작성 커뮤니티의 공개를 중단했습니다. 기존 문서를 공식 자료 분석과 재현 가능한 계산 예시로 다시 작성했습니다. <a href="/data-integrity.html">수정 내역 보기</a></p></div></section>`);

page('games/index.html','게임별 거래·정산·기록 가이드','11개 게임의 거래 구조와 시간·비용 기록 기준을 공식 출처와 함께 확인하세요.',`<section class="hero"><span class="eyebrow">GAME GUIDES</span><h1>게임이 다르면,<br>기록할 기준도 달라집니다.</h1><p class="lead">거래소가 있다는 사실만으로 현금 수익을 추정할 수는 없습니다. 게임마다 다른 정산 방식, 시간 기준과 재화 단위를 확인하세요.</p></section><label for="gameSearch">게임명 또는 주제 찾기</label><br><input class="search" id="gameSearch" type="search" placeholder="예: 메이플, 정산, 시간"><p class="meta" id="searchStatus" role="status">11개 가이드</p><div class="cards">${games.map(gameCard).join('')}</div><section class="article"><h2>이 목록은 수익 순위가 아닙니다</h2><p>정산 구조가 비교적 명확한 문서부터, 시간·표본 조건을 따져야 하는 문서, 신작 자료를 검토하는 문서 순으로 배치했습니다. 카드의 재화 단위는 기록에 쓰는 구분이며 원화 가치나 게임 간 우열을 뜻하지 않습니다.</p><p>공식 자료에서 확인한 사실과 이 사이트의 해석을 문서 안에서 분리했습니다. 수수료나 서비스 규칙이 바뀌면 게임 내 표시와 최신 공식 공지를 우선 확인하고, 기존 기록에는 측정 당시 조건을 남겨야 합니다.</p></section>`);

for(const g of games){const body=`<p class="lead">${esc(g.lead)}</p><h2 id="facts">${esc(g.factsLabel||'공식 자료에서 확인한 내용')}</h2>${para(g.facts)}<p class="meta">이 절의 확인 출처는 문서 하단에 연결했습니다. 아래 분석과 숫자 예시는 쌀먹지수의 설명이며 운영사가 발표한 수익 통계가 아닙니다.</p><h2 id="analysis">기록할 때 달라지는 판단</h2>${para(g.analysis)}<h2 id="record">${esc(g.name)} 기록표에 남길 항목</h2>${table(['구분','확인·기록할 내용','피해야 할 혼동'],g.rows)}<h2 id="example">숫자로 살펴보는 계산 예시</h2><span class="example-label">실측 아님 · 설명용 가정</span><p>${esc(g.example)}</p><h2 id="steps">실제로 기록하는 순서</h2><ol>${g.steps.map(p=>'<li>'+esc(p)+'</li>').join('')}</ol><h2 id="limits">이 자료로 결론 낼 수 있는 범위</h2><p>${esc(g.conclusion)}</p><p>직접 플레이한 회차나 거래 증빙을 제시하는 체험기가 아닙니다. 자신의 관측은 <a href="/calculator.html">기록 계산기</a>에 입력하고, 측정 범위는 <a href="/blog/beginner-guide-2026.html">첫 기록 안내</a>에 따라 남길 수 있습니다.</p>`;articlePage('games/'+g.slug+'.html',g.name+' — '+g.topic,g.lead,body,g.sources,'게임별 가이드');}
page('blog/index.html','게임 수익 숫자를 읽는 분석 노트','시급 비교 오류, 개인 기록법, 게임 간 비교와 신작 예측을 재현 가능한 계산 예제로 분석합니다.',`<section class="hero"><span class="eyebrow">ANALYSIS NOTES</span><h1>높은 숫자보다<br>비교가 가능한 숫자.</h1><p class="lead">시간·단위·정산·표본을 구분하면 같은 자료도 다르게 보입니다. 계산을 직접 따라 할 수 있는 분석과 기록 방법을 모았습니다.</p></section><div class="cards">${articles.map(blogCard).join('')}</div><section class="article"><h2>읽는 순서</h2><p>처음 기록한다면 ‘첫 플레이 기록’을 읽고 계산기에 한 회차를 입력하세요. 기록이 여러 개 생겼다면 계산 방법의 시간 가중 평균을 확인할 수 있습니다. 게임 간 비교나 신작 전망을 볼 때에는 수익 비교 오류와 출처 검토 글을 함께 읽으면 무엇이 아직 확인되지 않았는지 판단하기 쉽습니다.</p><p>이 문서들은 직접 플레이한 후기가 아닙니다. 공식 자료의 확인 내용, 이 사이트의 해석, 가상 계산을 구분해서 표시합니다. 이전의 근거 없는 시급·예측 문구는 수정 내역에 공개했습니다.</p></section>`);
for(const a of articles)articlePage('blog/'+a.slug+'.html',a.title,a.description,a.body,a.sources);

page('calculator.html','개인 플레이 기록 계산기','수입·비용·경과 시간을 입력해 순증가와 시간당 값을 계산하고 같은 게임·단위의 기록을 합산합니다. 브라우저 저장 및 CSV 내보내기를 지원합니다.',`
<section class="hero"><span class="eyebrow">PERSONAL RECORD CALCULATOR</span><h1>내가 기록한 만큼,<br>계산도 투명하게.</h1><p class="lead">게임·활동별 수입과 비용을 같은 재화 단위로 입력하세요. 공개 시세를 가져오거나 기록을 서버에 전송하지 않습니다.</p></section>
<section class="calculator" aria-label="개인 기록 입력"><form id="recordForm"><fieldset id="calculatorFields" disabled><legend class="sr-only">개인 기록 계산 입력</legend><div class="form-grid"><div class="field"><label for="game">게임·활동 이름</label><input id="game" name="game" aria-describedby="gameHint" maxlength="60" required placeholder="예: 로스트아크 / 생활 / 서버명"><small id="gameHint">서버·활동 조건이 다르면 이름을 나눠주세요.</small></div><div class="field"><label for="date">기록 날짜</label><input type="date" id="date" name="date" required></div><div class="field"><label for="unit">같은 단위로 입력</label><select id="unit" name="unit" aria-describedby="unitHint">${['골드','메소','은화','다이아','BP','원'].map(u=>'<option>'+u+'</option>').join('')}</select><small id="unitHint">원화는 실제 현금 활동 장부에만 사용합니다. 게임 재화 환전 기능이 아닙니다. 목록에 없는 재화는 <a href="/downloads/record-template.csv" download>빈 CSV 양식</a>에 정확한 단위명으로 기록하세요.</small></div><div class="field"><label for="basis">기록 유형</label><select id="basis" name="basis"><option value="actual">본인 기록 (내용 미검증)</option><option value="example">계산 예시 (가상 수치)</option></select></div>
${[['revenue','수입','정산 전 판매금을 쓰면 수수료를 따로 입력하세요. 순수령액을 쓰면 수수료는 0입니다.'],['fee','실제 수수료','이미 차감된 비용은 다시 빼지 않습니다. 없으면 0을 입력하세요.'],['cost','기타 소비 비용','같은 단위의 소모품·수리·입장 비용. 다른 단위 비용은 메모로 남깁니다.'],['minutes','경과 시간 (분)','준비·이동·대기 등 포함 범위를 메모하세요. 0.01분 이상, 소수 둘째 자리까지 입력하세요.'],['active','직접 조작 시간 (분)','미산정은 0으로 입력하세요. 측정값은 0.01분 단위이며 경과 시간보다 길 수 없습니다.']].map(([name,label,hint])=>'<div class="field"><label for="'+name+'">'+label+'</label><input type="number" step="'+(['minutes','active'].includes(name)?'0.01':'any')+'" min="'+(name==='minutes'?'0.01':'0')+'" max="1000000000000000" id="'+name+'" name="'+name+'" required inputmode="decimal" aria-describedby="'+name+'Hint"><small id="'+name+'Hint">'+hint+'</small></div>').join('')}<div class="field wide"><label for="memo">측정 조건 메모</label><input id="memo" name="memo" aria-describedby="memoHint" maxlength="500" placeholder="버전·장비·미판매 재고·제외한 비용 등"><small id="memoHint">비밀번호·인증 코드·개인 연락처는 적지 마세요.</small></div></div><div class="actions"><button type="submit" class="primary">계산하기</button><button type="button" id="exampleBtn">가상 예시 불러오기</button><button type="button" id="saveBtn">이 브라우저에 기록 저장</button></div></fieldset></form><div id="result" hidden><p class="meta" id="resultBasis"></p><div class="result"><div class="metric"><span>순증가</span><strong id="netResult"></strong></div><div class="metric"><span>경과 시간당</span><strong id="hourResult"></strong></div><div class="metric"><span>직접 조작 시간당</span><strong id="activeResult"></strong></div></div></div><p class="status" id="calcStatus" role="status" aria-live="polite">계산기 준비 중입니다. 입력이 활성화되지 않으면 아래 계산식과 CSV 양식을 이용하세요.</p><noscript><p class="note">계산기 동작에는 JavaScript가 필요하며, 비활성 상태에서는 입력과 제출이 잠겨 있습니다. 아래 계산식과 <a href="/downloads/record-template.csv">CSV 기록 양식</a>은 JavaScript 없이도 확인할 수 있습니다.</p></noscript></section>
<section><div class="section-head"><h2>이 브라우저의 기록</h2><button type="button" id="exportBtn" disabled>CSV 다운로드</button></div><p id="emptyRecords">저장한 기록이 없습니다. 기록은 저장 버튼을 눌러야 남습니다.</p><div class="table-scroll" id="recordsTable" hidden><table><caption>개인 입력 기록 · 공개 통계에 반영되지 않음</caption><thead><tr><th scope="col">날짜</th><th scope="col">게임·활동</th><th scope="col">순증가</th><th scope="col">경과 시간</th><th scope="col">관리</th></tr></thead><tbody id="recordRows"></tbody></table></div><div id="summary"></div><p class="meta">같은 게임·활동명, 단위, 기록 유형끼리만 합산합니다. 서버·패치 조건이 다르면 활동 이름을 구분하세요. 최대 500개를 보관하며 브라우저 데이터 삭제 시 기록이 사라집니다.</p></section>
<section class="article"><h2>계산식과 입력 예시</h2><div class="formula">순증가 = 수입 − 수수료 − 기타 비용<br>경과 시간당 = 순증가 × 60 ÷ 경과 분</div><p>가상으로 수입 10,000골드, 수수료 500골드, 비용 1,500골드, 경과 시간 90분을 입력하면 순증가는 8,000골드, 경과 시간당 약 5,333.33골드입니다. 순수령액 9,500골드를 수입으로 입력했다면 수수료는 0으로 둬야 같은 결과가 나옵니다.</p><p>미판매 물품의 가격, 반환받은 보증금, 계정 사이의 재화 이동을 새 수입으로 합산하지 마세요. 비용이 확인되지 않았다면 0을 입력한 결과는 해당 비용을 제외한 계산이라는 점을 메모해야 합니다.</p><h2>계산값을 해석할 때</h2><p>음수는 입력한 비용이 수입보다 컸다는 뜻입니다. 경과 시간은 0.01분 이상이고 시간은 소수 둘째 자리까지 입력합니다. 조작 시간 0은 미산정으로 표시합니다. 기록별 최솟값·최댓값은 실제 입력 범위이며 신뢰구간이나 수익 보장 범위가 아닙니다.</p><p>계산기에는 실시간 시세·원화 환율·게임별 평균 시급을 넣지 않았습니다. 입력한 값의 진위는 확인하지 않으므로 계산이 맞는 것과 자료가 검증된 것은 다릅니다. <a href="/blog/ssalmuk-methodology.html">전체 계산 방법</a>과 <a href="/blog/beginner-guide-2026.html">기록 기준</a>을 함께 확인하세요.</p></section>`,{script:'<script src="/assets/calculator-core.js" defer></script><script src="/assets/calculator.js" defer></script>'});

const simple=(file,title,description,body)=>page(file,title,description,'<article class="article" style="max-width:800px"><h1>'+esc(title)+'</h1><p class="meta">최종 수정 '+date+'</p>'+body+'</article>');
simple('guide.html','쌀먹지수 이용 안내','게임별 공식 자료를 확인하고 개인 기록을 계산·저장·내보내는 방법을 안내합니다.',`<p class="lead">쌀먹지수는 게임 경제의 구조와 자신의 플레이 기록을 읽는 사이트입니다. 공개 시급 순위를 따라 게임을 선택하기보다, 어떤 재화가 실제로 남는지 확인하도록 돕습니다.</p><h2>1. 게임별 기록 기준 확인</h2><p><a href="/games/">게임별 가이드</a>에서 자신이 하는 게임을 찾으세요. 공식 자료로 확인한 내용과 문서의 해석을 나누어 제공합니다. 판매 수령액, 보증금, 피로도, 메소·포인트 구분처럼 게임마다 다르게 기록해야 할 부분을 먼저 살펴봅니다.</p><h2>2. 한 가지 활동을 측정</h2><p>시작 날짜와 서버, 장비, 버프, 포함할 시간을 정합니다. 끝난 뒤 실제 판매금과 소비 자원, 미판매 재고를 나눠 적습니다. 일회성 보상이나 이벤트 적용 여부도 기록해야 다음 회차와 비교할 수 있습니다.</p><h2>3. 계산기에 입력</h2><p><a href="/calculator.html">기록 계산기</a>에 게임·활동 이름, 단위, 수입, 비용, 시간을 입력합니다. 수입이 정산 전 금액이면 수수료를 차감하고, 이미 정산된 금액이면 수수료는 0으로 둡니다. 가상 예시는 실제 기록과 별도로 분류하세요.</p><h2>4. 같은 조건의 결과끼리 비교</h2><p>여러 회차는 전체 순증가를 전체 경과 시간으로 나눕니다. 짧은 회차의 높은 수치만 선택하지 않고 손해와 중단이 있는 날도 함께 기록합니다. 서로 다른 게임이나 단위를 하나의 원화 수익 순위로 바꾸지 않습니다.</p><h2>5. 저장과 내보내기</h2><p>‘이 브라우저에 기록 저장’을 누르면 현재 기기의 로컬 저장소에 남습니다. 다른 기기로 자동 동기화되지 않으며 서버로 업로드하지 않습니다. CSV 다운로드로 외부에 보관할 수 있고, 개별 기록은 삭제 버튼으로 지울 수 있습니다. 내보낸 파일의 조건 메모에 개인 정보가 포함되지 않았는지 확인하세요.</p><h2>계산기 없이 기록하기</h2><p><a href="/downloads/record-template.csv" download>빈 기록 양식 CSV</a>를 내려받아 스프레드시트에서 사용할 수 있습니다. 순증가 = 수입 − 수수료 − 기타 비용, 시간당 값 = 순증가 × 60 ÷ 경과 분입니다. 같은 항목을 기록하면 도구를 바꿔도 비교 기준을 유지할 수 있습니다.</p><h2>질문과 정정 요청</h2><p>시세가 다르다는 제보에는 게임·서버·날짜·정산 조건이 있어야 원인을 살펴볼 수 있습니다. 공식 문서가 변경되었다면 URL과 바뀐 부분을 <a href="/contact.html">문의 페이지</a>로 알려주세요. 근거가 없는 수익 보장, 계정 거래·매크로 사용 방법은 이 사이트의 콘텐츠 범위에 포함하지 않습니다.</p>`);
simple('about.html','쌀먹지수와 운영자 소개','개인 운영 사이트 쌀먹지수의 목적, 공개 자료의 범위와 운영 연락처를 안내합니다.',`<p class="lead">쌀먹지수는 게임별 경제 구조와 개인 플레이 기록을 이해하기 위한 1인 운영 사이트입니다. 운영 표기는 ‘쌀먹지수 운영자’이며, 연락처는 <a href="mailto:ssalmukindex@gmail.com">ssalmukindex@gmail.com</a>입니다.</p><h2>어떤 문제를 해결하려 하나요?</h2><p>게임 수익을 다룬 글에는 단위·서버·기간·비용이 빠진 숫자가 자주 등장합니다. 이 사이트는 수치의 높낮이를 말하기 전에 무엇을 측정했는지 확인하는 방법을 제공합니다. 판매가와 수령액, 게임 내 재화와 현금, 접속 시간과 조작 시간을 구분하는 데 집중합니다.</p><h2>직접 제공하는 것</h2><p>게임별 공식 자료를 대조한 기록 가이드, 재현 가능한 가상 계산 분석, 개인 기록을 계산·저장·내보내는 도구를 제공합니다. 공식 설명을 그대로 모으는 데서 그치지 않고 어떤 입력을 남겨야 잘못된 비교를 피할 수 있는지 표와 예제로 풀어냅니다.</p><h2>경험과 자격에 대한 표시</h2><p>운영자가 모든 게임을 직접 플레이했거나 수익을 실측했다고 주장하지 않습니다. 공개한 게임별 원화 평균 수익 표본도 없습니다. 문서 조사·초안 작성·코드 제작에는 AI 도구를 사용하며, 내용은 출처가 확인되는 사실과 계산 예시로 구분합니다. 별도의 취재팀이나 게임 전문가 자격을 내세우지 않습니다.</p><h2>과거 자료의 정정</h2><p>초기 버전에는 근거가 확인되지 않은 시급 수치와 자동 작성 글이 있었습니다. 이를 실제 경험과 참여로 이해할 수 있는 문제가 있어 공개를 중단하고 문서를 다시 작성했습니다. <a href="/data-integrity.html">정정 기록</a>에 변경 이유와 범위를 남겼습니다.</p><h2>운영과 광고</h2><p>현재 사이트는 무료로 열람할 수 있습니다. 광고 계정 연결을 위한 메타 태그와 ads.txt를 제공하지만 공개 페이지에서 광고·방문자 분석 스크립트는 실행하지 않습니다. 광고를 추가할 때에는 실제 구성에 맞게 개인정보 안내와 표시 방식을 갱신해야 합니다.</p><h2>연락하기</h2><p>오류가 있는 문장의 URL, 잘못된 내용과 확인 가능한 공식 출처를 함께 보내주시면 검토할 수 있습니다. 응답 시한이나 정정 채택을 보장하지 않습니다. 문의 방법은 <a href="/contact.html">연락처 페이지</a>에서 확인하세요.</p>`);
simple('editorial.html','편집·출처·계산 예시 기준','공식 사실과 해석, 가상 계산을 구분하고 문서를 정정하는 기준을 공개합니다.',`<p class="lead">문장의 근거를 확인할 수 있어야 숫자도 평가할 수 있습니다. 쌀먹지수는 공식 자료의 설명과 자체 해석, 설명용 숫자를 구분합니다.</p><h2>공식 사실</h2><p>게임사 가이드·공지·공식 배포자의 제품 설명을 우선합니다. 공식 도메인에 있는 이용자 게시판 글은 운영사 발표와 구분합니다. 출처 제목, 링크, 확인한 범위를 문서 끝에 표시합니다. 출처가 기능의 존재만 설명하면 이를 실제 수익을 증명하는 근거로 사용하지 않습니다.</p><h2>해석과 계산</h2><p>기록 항목의 선택과 비교 방식은 이 사이트의 분석입니다. 가상의 숫자는 ‘계산 예시’로 표시하고 특정 게임의 실측 결과처럼 쓰지 않습니다. 독자가 식과 입력값으로 결과를 다시 계산할 수 있게 합니다. 원화 환율이나 거래 가능성을 임의로 만들어 넣지 않습니다.</p><h2>실제 플레이 자료</h2><p>직접 경험했다고 쓰려면 누가, 언제, 어떤 조건에서 측정했는지 설명할 자료가 필요합니다. 현재 가이드는 직접 플레이 후기나 인증된 수익 통계가 아닙니다. 사이트의 댓글 수, 조회 수, 초기 숫자를 수익 검증의 근거로 쓰지 않습니다.</p><h2>갱신과 정정</h2><p>수수료·보상·출시 일정처럼 변하는 내용은 확인일을 남깁니다. 과거 발표는 당시 조건을 설명하는 데만 사용합니다. 출처와 문서가 어긋나면 해당 문장을 확인·정정하고 중요한 변경은 <a href="/data-integrity.html">정정 기록</a>에 남깁니다. 최신 상태를 상시 자동 검증하는 서비스는 아닙니다.</p><h2>AI 도구 사용</h2><p>자료 조사와 문서 초안, 계산기 코드 제작에 AI 도구를 사용합니다. 자동으로 체험담이나 이용자 참여를 만들어 게시하지 않습니다. AI가 작성했다는 이유로 사실이라고 간주하지 않으며, 공식 출처에서 확인되지 않은 수익 주장을 채워 넣지 않습니다.</p><h2>자료 제보</h2><p>공식 문서 링크, 해당 문장, 확인일을 <a href="/contact.html">문의 주소</a>로 보내주세요. 실제 기록을 제보할 때에는 게임·서버·활동·시간·정산·비용을 구분하고 개인 정보는 제거해야 합니다. 제보는 공개 게시판에 자동 등록되지 않습니다.</p>`);
simple('contact.html','문의·오류 정정 요청','쌀먹지수 운영자에게 문서 오류, 계산기 문제, 기존 게시글 및 개인정보 관련 요청을 보내는 방법입니다.',`<p class="lead">운영 연락처: <a href="mailto:ssalmukindex@gmail.com">ssalmukindex@gmail.com</a></p><p>메일 프로그램을 사용하지 않는 경우 주소를 복사해 이용하는 메일 서비스에서 작성해주세요. 이 페이지는 문의 내용을 자동 전송하는 폼이 아닙니다.</p><h2>문서 오류를 알려주실 때</h2><ul><li>오류가 있는 페이지 URL과 문장</li><li>문제가 되는 이유와 공식 출처 URL</li><li>확인한 날짜·서버·버전 등 적용 범위</li></ul><p>‘시급이 다르다’는 설명만으로는 어떤 조건이 다른지 확인하기 어렵습니다. 이 사이트는 고정 원화 시급 순위를 제공하지 않으며 실제 관측 자료와 계산 예시를 구분합니다.</p><h2>계산기 문제를 알려주실 때</h2><p>브라우저와 기기, 입력한 숫자·단위, 기대 결과와 표시 결과를 알려주세요. 비밀번호나 인증 코드, 계정 접속 정보는 보내지 마세요. 저장 기록은 브라우저에만 있으므로 운영자가 원격으로 열람하거나 복구할 수 없습니다.</p><h2>기존 커뮤니티 글과 개인정보 요청</h2><p>과거 게시글 원본은 공개 화면과 분리해 보존되어 있습니다. 본인 글의 삭제·정정 또는 개인정보 관련 요청에는 게임명, 작성 시점, 내용 일부 등 식별할 정보를 제공해주세요. 작성자 확인이 필요한 경우 추가 확인을 요청할 수 있습니다. 공개가 중단되었다는 것이 서버 원본까지 삭제되었다는 뜻은 아닙니다.</p><h2>답변과 반영</h2><p>개인 운영으로 즉시 응답이나 정해진 처리 기간을 보장하지 않습니다. 제보 내용과 근거를 확인한 뒤 반영 여부를 판단합니다. 게임 계정 문제나 게임사 제재 이의 신청은 해당 게임의 공식 고객센터를 이용해주세요.</p><p><a href="/editorial.html">편집 기준</a> · <a href="/privacy.html">개인정보처리방침</a></p>`);
simple('privacy.html','개인정보처리방침','개인 기록 계산기의 브라우저 저장, 외부 전송 범위, 기존 커뮤니티 자료와 문의 방법을 안내합니다.',`<p>적용일: 2026년 9월 14일. 이 문서는 현재 공개 사이트의 데이터 처리 동작을 설명합니다. 운영 연락처는 <a href="mailto:ssalmukindex@gmail.com">ssalmukindex@gmail.com</a>입니다.</p><h2>개인 기록 계산기</h2><p>입력한 게임·활동명, 날짜, 단위, 금액, 시간, 메모는 브라우저에서 계산합니다. ‘이 브라우저에 기록 저장’을 누르면 localStorage의 ssalmuk_records_v1 항목에 저장합니다. 입력값을 사이트 서버나 Firebase에 전송하지 않습니다. 회원가입, 브라우저 지문 생성, 공개 투표 집계 기능을 사용하지 않습니다.</p><h2>보관과 삭제</h2><p>저장 기록은 이용자가 개별 삭제하거나 해당 사이트의 브라우저 저장 데이터를 삭제할 때까지 남을 수 있습니다. 시크릿 모드 종료·기기 변경·브라우저 정리 시 사라질 수 있습니다. CSV로 내려받은 파일은 이용자의 기기에 별도로 저장되며 사이트에서 삭제할 수 없습니다. 운영자는 로컬 기록에 접근하거나 복구할 수 없습니다.</p><h2>웹 호스팅과 외부 링크</h2><p>정적 사이트는 GitHub Pages에서 제공합니다. 페이지를 요청할 때 IP 주소, 접속 정보 등 통신에 필요한 정보는 호스팅 제공자에게 전달될 수 있습니다. <a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement">GitHub 개인정보 안내</a>를 참고하세요. 외부 출처 링크를 클릭하면 해당 사이트의 데이터 처리 방식이 적용됩니다.</p><h2>광고와 분석 코드</h2><p>현재 공개 페이지는 광고 계정 식별용 메타 태그와 ads.txt만 제공합니다. Google AdSense 광고 로더, Google Analytics, Firebase 클라이언트 스크립트를 실행하지 않습니다. 광고·분석 기능을 추가하면 그 처리 범위와 동의 방식을 실제 구성에 맞게 갱신해야 합니다.</p><h2>과거 커뮤니티 자료</h2><p>이전 버전은 닉네임, 글·답글 본문, 작성 시각, PIN 해시, 투표와 브라우저 식별 관련 기록을 Firebase에 저장했습니다. 현재 공개 페이지는 해당 자료를 읽거나 새 글을 저장하지 않지만, 기존 서버 원본을 이번 개편에서 일괄 삭제한 것은 아닙니다. 서버 자료의 삭제·정정 요청은 운영 연락처로 문의할 수 있습니다. 브라우저 저장소를 지워도 과거 서버 글이 함께 삭제되지는 않습니다.</p><h2>이메일 문의</h2><p>이메일을 보내면 발신 주소와 문의 내용이 운영자 및 메일 서비스에 전달됩니다. 문의 확인과 답변을 위해 사용하며 비밀번호·인증 코드·결제 정보를 보내지 않도록 안내합니다. 메일 관련 삭제 요청도 같은 연락처로 보낼 수 있습니다.</p><h2>방침 변경과 문의</h2><p>서비스 동작이 바뀌면 적용일과 내용을 갱신합니다. 현재 안내와 실제 동작이 다른 부분을 발견한 경우 <a href="/contact.html">문의 페이지</a>의 주소로 알려주세요.</p>`);
simple('data-integrity.html','데이터·콘텐츠 정정 기록','자동 작성 글, 초기 시급과 과장된 신뢰도 표시를 정정한 내역과 현재 제공 범위를 공개합니다.',`<p class="lead">초기 사이트에는 자동 작성된 체험담과 출처가 확인되지 않은 원화 시급이 실제 이용자 데이터처럼 보이는 문제가 있었습니다. 면책 문구만 추가하는 것으로 충분하지 않아 공개 구조와 문서를 바꿨습니다.</p><h2>2026-09-14 · 공개 콘텐츠 전면 정정</h2><ul><li>검증된 원자료가 없는 원화 시급 순위와 신작 수익 예측을 공개하지 않습니다.</li><li>자동 작성 글·초기 투표 수·신뢰도·HOT 등 참여 규모를 오해하게 하는 표시를 제거했습니다.</li><li>공개 커뮤니티 및 제보 입력을 중단했습니다. 과거 원본은 보존하며 새 공개 페이지에서는 읽거나 쓰지 않습니다.</li><li>게임별 가이드 11개와 분석 노트 5개를 공식 자료의 확인 범위와 재현 가능한 계산 예시로 다시 작성했습니다.</li><li>카프라스의 돌을 내구도 회복용으로 설명한 오류, 게임 재화와 현금 수입의 혼동, 초기값을 실제 표본으로 해석한 설명을 정정했습니다.</li><li>개인 기록 계산기를 추가했습니다. 가상 예시와 본인 기록, 게임·재화 단위를 구분하며 공개 통계로 전송하지 않습니다.</li></ul><h2>2026-09-11 · 자동 작성 경로와 표시의 1차 정리</h2><p>먼저 자동 생성 경로를 제거하고, 당시 읽은 5,741개 글 중 자동 생성 근거가 확인된 5,710개를 표시에서 제외했습니다. 남은 31개도 작성 경로가 확인된 실제 이용자 글로 인증하지 않았습니다. 이후 이번 개편에서 공개 커뮤니티 자체를 중단했습니다. 이 개수는 정리 당시의 기록이며 현재 참여 지표가 아닙니다.</p><h2>시급 숫자를 유지하지 않은 이유</h2><p>초기 추정값에 제보를 혼합한 기존 수치는 날짜·서버·실제 시간·거래 정산·비용 증빙과 연결되지 않았습니다. ‘미검증’이라고 표시해도 높은 원화 숫자의 비교가 주는 인상을 없애기 어려워 순위의 공개를 중단했습니다. 현재 계산기는 이용자가 입력한 값을 정해진 식으로 계산하는 별도 기능입니다.</p><h2>이전 URL과 자료</h2><p>게임별 문서와 분석 글의 URL은 유지하되 제목과 내용을 새 범위에 맞게 정정했습니다. 과거 글을 체험기나 수익 증빙으로 재사용하지 않습니다. 실제 기록을 공개하게 된다면 측정자·조건·기간·정산·비용을 함께 제시해야 합니다.</p><h2>오류 제보와 기존 글 요청</h2><p>누락된 오류나 본인 과거 게시글의 삭제·정정 요청은 <a href="/contact.html">문의 페이지</a>로 알려주세요. 공개 화면에서 제외한 것과 원본을 삭제한 것은 다릅니다. 출처와 데이터 처리 범위는 <a href="/editorial.html">편집 기준</a>과 <a href="/privacy.html">개인정보처리방침</a>에 설명합니다.</p>`);
page('404.html','페이지를 찾을 수 없습니다','요청한 주소에 문서가 없습니다. 게임별 가이드와 기록 계산기에서 필요한 내용을 찾아보세요.',`<section class="hero"><span class="eyebrow">404</span><h1>이 주소에 문서가 없습니다.</h1><p class="lead">주소를 확인하거나 아래 목록에서 필요한 내용을 찾아보세요.</p><div class="actions"><a class="button primary" href="/">홈으로</a><a class="button" href="/games/">게임별 가이드</a><a class="button" href="/calculator.html">기록 계산기</a></div></section>`,{noindex:true});

files.set('downloads/record-template.csv','\uFEFF날짜,게임·활동,단위,실제기록또는계산예시,수입,실제수수료,기타비용,경과분,조작분,조건메모\r\n');
const urls=[...files.keys()].filter(f=>f.endsWith('.html')&&f!=='404.html').map(f=>base+(f==='index.html'?'/':f.endsWith('/index.html')?'/'+f.slice(0,-10):'/'+f));
files.set('sitemap.xml','<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+urls.map(url=>'  <url><loc>'+url+'</loc><lastmod>'+date+'</lastmod></url>').join('\n')+'\n</urlset>\n');
files.set('robots.txt','User-agent: *\nAllow: /\n\nSitemap: '+base+'/sitemap.xml\n');
if(process.argv.includes('--check')){let fail=0;for(const [file,content]of files){if(!fs.existsSync(path.join(out,file))||fs.readFileSync(path.join(out,file),'utf8').replace(/\r\n/g,'\n')!==content.replace(/\r\n/g,'\n')){console.error('Generated file differs: '+file);fail++;}}process.exitCode=fail?1:0;console.log('Checked '+files.size+' generated files');}
else{for(const [file,content]of files){fs.mkdirSync(path.dirname(path.join(out,file)),{recursive:true});fs.writeFileSync(path.join(out,file),content);}console.log('Built '+files.size+' files; '+urls.length+' indexable pages');}
